#!/bin/sh

# ** Change the path to your original git **
git="/usr/bin/git"
#

ps=$(ps -o stat= -p $PPID)
check=$($git rev-parse --is-inside-work-tree)

if [ $ps != "S+" ] && [ $check == "true" ]; then
	timestamp=$(date +"%Y%m%d-%H%M%S")
	before_sha=$($git rev-parse --verify HEAD)
	echo LOG,"$timestamp,$(pwd),$@,$before_sha" >> $HOME/.git_history
fi

if [ $check == "true" ]; then
	$git $@
fi
