#!/bin/sh
ps=$(ps -o stat= -p $PPID)

if [ $ps != "S+" ]; then
	timestamp=$(date +"%Y%m%d-%H%M%S")
	before_sha=$(git rev-parse --verify HEAD)
	echo LOG,"$timestamp,$(pwd),$@,$before_sha" >> $HOME/.git_history
fi

# ** Change the path to your original git **
# /usr/bin/git $@
/usr/bin/git $@
