#!/bin/sh
REPOSITORY_ROOT_PATH=`command git rev-parse --show-toplevel 2> /dev/null`

OUTPUT=$*
TIMESTAMP=`date +%s`
SHA=`command git rev-parse --verify HEAD`
USER_NAME=`command git config user.name`
USER_EMAIL=`command git config user.email`

echo \{\"ts\":$TIMESTAMP,\"type\":\"REWRITE\",\"output\":\"$OUTPUT\",\"user_name\":\"$USER_NAME\",\"user_email\":\"$USER_EMAIL\",\"sha\":\"$SHA\",\"details\":\[ >> $REPOSITORY_ROOT_PATH/.git/.git_history

DETAILS=""
while read i; do
	DETAILS="$DETAILS\"$i\","
done
echo ${DETAILS%?} >> $REPOSITORY_ROOT_PATH/.git/.git_history
echo \]\}, >> $REPOSITORY_ROOT_PATH/.git/.git_history
