#!/bin/sh
REPOSITORY_ROOT_PATH=`command git rev-parse --show-toplevel 2> /dev/null`

OUTPUT=$*
TIMESTAMP=`date +%s`
SHA=`command git rev-parse --verify HEAD`
USER_NAME=`command git config user.name`
USER_EMAIL=`command git config user.email`

echo \{\"ts\":$TIMESTAMP,\"type\":\"CHECKOUT\",\"output\":\"$OUTPUT\",\"user_name\":\"$USER_NAME\",\"user_email\":\"$USER_EMAIL\",\"sha\":\"$SHA\"\}, >> $REPOSITORY_ROOT_PATH/.git/.git_history
